name: build
on: [pull_request, push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Prepare environment
        run: |
          chmod +x gradlew
          sudo apt-get install apksigner
          keytool -genkey -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 1095 -dname "C=US, O=Android, CN=Android Debug"
      - name: Test the app
        run: ./gradlew test
      - name: Build debug app
        run: |
          ./gradlew assembleDebug
          ./gradlew bundleDebug
      - name: Build release app
        run: |
          ./gradlew assembleRelease
          apksigner sign --ks debug.keystore --ks-key-alias androiddebugkey --ks-pass pass:android app/build/outputs/apk/release/app-release-unsigned.apk
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release.apk
          ./gradlew bundleRelease
      - name: Sort files
        run: |
          mkdir output
          mv app/build/outputs/apk/release/app-release.apk output
          mv app/build/outputs/bundle/release/app-release.aab output
          mv app/build/outputs/apk/debug/app-debug.apk output
          mv app/build/outputs/bundle/debug/app-debug.aab output
      - name: Upload debug
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.zip
          path: output/app-debug.*
      - name: Upload release
        uses: actions/upload-artifact@v3
        with:
          name: app-release.zip
          path: output/app-release.*
